# Generated by Django 3.1.1 on 2020-09-12 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CustomUser', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='destict',
            field=models.TextField(default='Ngaka Modiri Molema'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='phone_number',
            field=models.TextField(default='071271912'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='province',
            field=models.TextField(default='North West'),
        ),
    ]
