# Generated by Django 3.1.1 on 2020-09-12 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CustomUser', '0002_auto_20200912_1447'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='destict',
            new_name='destrict',
        ),
    ]
